#!/bin/bash

set -eux
set -o pipefail

source $(which ddd-env-vars)

tools_dir=$DDD_WORKDIR/tools
tools="https://git.openstack.org/openstack/diskimage-builder
https://git.openstack.org/openstack/dib-utils
https://github.com/jwerle/mush"

mkdir -p tools_dir

for tool in $tools; do
    tool_name=$(basename $tool)
    tool_dir="$tools_dir/$tool_name"
    if ! [ -d "$tool_dir" ]; then
        git clone $tool $tool_dir
    else
        pushd $tool_dir
        if echo "/$(git symbolic-ref -q HEAD)" | grep -q "/master\$" ; then
            git pull --ff-only
        fi
        popd
    fi
done
