#!/bin/bash

set -eux
set -o pipefail

source $(which ddd-env-vars)

vm_name=$1
image_path=$2
definition_path=$(mktemp)

mkdir -p $DDD_VM_DEFINITIONS_DIR

mush_exec=$DDD_MUSH_REPOLOCATION/mush.sh

cat $DDD_VM_TEMPLATE | \
    engine="kvm" \
    name="$vm_name" \
    memory="$DDD_VM_MEMORY" \
    cpus="$DDD_VM_CPUS" \
    emulator="$DDD_EMULATOR" \
    imagefile="$image_path" \
    $mush_exec | tee $definition_path

virsh define $definition_path
rm $definition_path
